name: test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install pytests
        run: |
          sudo apt-get update
          sudo apt-get install -y make python3 python3-pytest
      - name: Run tests
        run: make tests
